In [2]:
import pandas as pd
import numpy as np

In [3]:
ha_2015_older = pd.read_csv("happiness_2015_and_older.csv")

In [4]:
ha_2015_older = ha_2015_older.drop(columns=["Unnamed: 0"])

In [5]:
ha_2015_older.head()

,country,year,Score,GDP,Social support,Healthy life expectancy,Freedom,Confidence in national government
0,Austria,2006,7.122211,10.648226,0.936350,70.018700,0.941382,0.497038
1,Austria,2008,7.180954,10.692783,0.934593,70.501869,0.879069,0.257242
2,Austria,2010,7.302679,10.668132,0.914193,70.632278,0.895980,0.486447
3,Austria,2011,7.470513,10.692453,0.944157,70.985039,0.939356,0.406920
4,Austria,2012,7.400689,10.695439,0.945142,70.944412,0.919704,0.376574

In [6]:
ha_2016 = pd.read_csv("happiness_2016.csv")
ha_2016 = ha_2016.drop(columns=["Unnamed: 0"])
ha_2016["Year"] = 2016

In [7]:
ha_2017 = pd.read_csv("happiness_2017.csv")
ha_2017 = ha_2017.drop(columns=["Unnamed: 0"])
ha_2017 = ha_2017.rename(columns={" Generosity":"Generosity"})
ha_2017["Year"] = 2017

In [8]:
ha_2018 = pd.read_csv("happiness_2018.csv")
ha_2018 = ha_2018.drop(columns=["Unnamed: 0"])
ha_2018 = ha_2018.rename(columns={"Generosity importance":"Generosity"})
ha_2018["Year"] = 2018

In [9]:
ha_2016_later = pd.concat([ha_2016, ha_2017, ha_2018], axis=0, sort=False)
ha_2016_later = ha_2016_later.reset_index(drop=True)

In [10]:
ha_2016_later = ha_2016_later[["Country", "Year", "Score", "GDP", "Social support", "Healthy life expectancy", "Freedom", "Generosity", "Perceptions of corruption"]]
ha_2016_later["Confidence in national government"] = np.nan
ha_2016_later.head()

,Country,Year,Score,GDP,Social support,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption,Confidence in national government
0,Denmark,2016,7.526,1.441784,1.163745,0.795040,0.579413,0.361710,0.444532,NaN
1,Netherlands,2016,7.339,1.464684,1.029123,0.812309,0.552114,0.474158,0.299268,NaN
2,Sweden,2016,7.291,1.451810,1.087640,0.831212,0.582185,0.382538,0.408666,NaN
3,Austria,2016,7.119,1.450382,1.083833,0.805645,0.543552,0.328647,0.213484,NaN
4,Belgium,2016,6.929,1.425390,1.052487,0.819594,0.513538,0.242399,0.262476,NaN

In [11]:
ha_2015_older = ha_2015_older.rename(columns = {"year":"Year", "country":"Country"})
ha_2015_older["Generosity"] = np.nan
ha_2015_older["Perceptions of corruption"] = np.nan
ha_2015_older = ha_2015_older[["Country", "Year", "Score", "GDP", "Social support", "Healthy life expectancy", "Freedom", "Generosity", "Perceptions of corruption", "Confidence in national government"]]
ha_2015_older.head()

,Country,Year,Score,GDP,Social support,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption,Confidence in national government
0,Austria,2006,7.122211,10.648226,0.936350,70.018700,0.941382,NaN,NaN,0.497038
1,Austria,2008,7.180954,10.692783,0.934593,70.501869,0.879069,NaN,NaN,0.257242
2,Austria,2010,7.302679,10.668132,0.914193,70.632278,0.895980,NaN,NaN,0.486447
3,Austria,2011,7.470513,10.692453,0.944157,70.985039,0.939356,NaN,NaN,0.406920
4,Austria,2012,7.400689,10.695439,0.945142,70.944412,0.919704,NaN,NaN,0.376574

In [12]:
ha_all = pd.concat([ha_2015_older, ha_2016_later])

In [13]:
ha_all = ha_all.reset_index(drop=True)
ha_all.head()
ha_all.to_csv("./backup_raw_data/happiness_all_raw.csv", index=False)